name: rounded_floating_app_bar
description: A package provides an easy way to add rounded corner floating app bar in Flutter project.
version: 1.0.0
homepage: https://github.com/ibhavikmakwana/rounded_floating_app_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
